### ISSUE TITLE
Push a new version to pypi.org

### ISSUE THREAD

**Issue by bnewbold** [dissemin/wikiciteparser#16]
Hi @wetneb, I'd like to push a new version of this package to pypi.org. Either 0.2.2 or 0.3.0 (I'll do 0.3.0 unless you have a strong opinion).

I think you invited me to the project on pypi.org a few months ago, but I was having trouble logging in to my account and didn't accept the invitation at the time. If you re-invite now I can accept and then push. Either my `bnewbold` or `bnewbold-archive` accounts on pypi would be fine.

**Comment by wetneb** [comment]
Makes sense, thanks a lot for the initiative! Invite resent.
