### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by nemobis** [dissemin/wikiciteparser#6]
Just for the record

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/federico/.local/lib/python3.7/site-packages/wikiciteparser/parser.py", line 166, in parse_citation_template
    name = unicode(template.name)
NameError: name 'unicode' is not defined
```

**Comment by wetneb** [comment]
Yes it needs to be made compatible with Python 3 apparently!

**Comment by digi-ark** [comment]
I think I have solved this at least partially. See the PR https://github.com/dissemin/wikiciteparser/pull/7

**Comment by wetneb** [comment]
@digi-ark I have uploaded a new version to PyPI with Python 3 compatibility. I hope it works for you!
