### ISSUE TITLE
Support for bulk processing of XML dumps

### ISSUE THREAD

**Issue by bnewbold** [dissemin/wikiciteparser#8]
Hi! Thank you for creating and maintaining this helpful python library.

I am interested in generating snapshot wikipedia reference dumps, using the period bulk XML dumps and wikiciteparser. I am wondering if you know of an existing script, and whether you would accept a patch to this repository to support a helper script. If not, I can just create a separate small repository.

Another, already existing project, builds on wikictieparser to achieve the same goal using PySpark and generating parquet files, and was re-used as part of a recent "wcw" grant project: https://github.com/Harshdeep1996/cite-classifications-wiki

I'm thinking on doing something more like https://github.com/mediawiki-utilities/python-mwcites, which uses https://github.com/mediawiki-utilities/python-mwxml to iterate over the bulk dumps. I would then generate JSON lines files.

**Comment by bnewbold** [comment]
Here is a quick example script. On my laptop this does only 20 revisions/second, but I think that is fine:

https://gist.github.com/bnewbold/c5ca0630b42ee3e17947221e015e421c

**Comment by wetneb** [comment]
Hi! Sure, why not, we could also add this in this library :)
